from django.urls import path
from . import views

urlpatterns = [
    path('demo', views.index, name='demo'),
    path('new_interaction', views.index, name='new_interaction'),
    path('homepage', views.homepage, name ='homepage'),
    path('search', views.search, name='search'),
    path('coloringhome', views.coloringhome, name = 'coloringhome'),
    path('new', views.new, name = 'new'),
    path('popular', views.popular, name='popular'),
    path('destress', views.destress, name='destress'),
    path('animals', views.animals, name = 'animals'),
    path('autumn', views.autumn, name = 'autumn'),
    path('cute', views.cute, name='cute'),
    path('disney', views.disney, name = 'disney'),
    path('fashion', views.fashion, name='fashion'),
    path('fruit', views.fruit, name = 'fruit'),
    path('floral', views.floral, name='floral'),
    path('hobby', views.hobby, name = 'hobby'),
    path('love', views.love, name='love'),
    path('mandala', views.mandala, name = 'mandala'),
    path('music', views.music, name='music'),
    path('nature', views.nature, name = 'nature'),
    path('people', views.people, name='people'),
    path('places', views.places, name = 'places'),
    path('pixar', views.pixar, name='pixar'),
    path('random', views.random, name = 'random'),
    path('sports', views.sports, name = 'sports'),
    path('spring', views.spring, name='spring'),
    path('summer', views.summer, name = 'summer'),
    path('thanksgiving', views.thanksgiving, name='thanksgiving'),
    path('winter', views.winter, name = 'winter'),
    path('zendoodle', views.zendoodle, name='zendoodle'),
]
